# Generated by Django 5.1.4 on 2024-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_mgmt', '0002_node_alter_baseitem_node'),
        ('project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
