# Generated by Django 5.1.4 on 2024-12-30 14:52

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_mgmt', '0001_initial'),
        ('project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content_mgmt.node')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_mgmt.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content_mgmt.node'),
        ),
    ]
