# Generated by Django 5.1.4 on 2024-12-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_mgmt', '0002_node_alter_baseitem_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
